### PR TITLE
There's no Format argument anymore

### PR DESCRIPTION
**Pull request by ilpianista**
See issue #12

### CODE REVIEW

**Comment by rkeithhill** [comment]
The file is appearing to GitHub as binary.  Perhaps an encoding issue?  The files were originally created by PowerShell as UTF-16LE.  I wonder if that is what is causing the problem?  If the file is in that format, try saving as UTF8 and commit/push that.

**Comment by ilpianista** [comment]
Uhm, I used the online editor.

**Comment by rkeithhill** [comment]
When you did that, did you see this warning?
```
We've detected the file encoding as UTF-16LE. When you commit changes we will transcode it to UTF-8. 
```
Of course, if it did convert to UTF-8 I'm not sure why the diff for this PR fails.

**Comment by ilpianista** [comment]
@rkeithhill please take a look now.

**Comment by rkeithhill** [comment]
I'm not sure what is going on with Git but I still see this: 
image

I'll make the change on my side. Thanks for pointing out the issue!

**Comment by ilpianista** [comment]
Yes, that's because Git cannot diff UTF-16 files.

**Pull request closed without merging**
