### PR TITLE
Add all exported cmdlets and functions to readme. Fixes #39.

### LINKED ISSUE #39: README should mention full set of commands! [pull request included!]
This is a really useful module, but people won't know the commands included until they install it. The README should mention the full set of included commands.

### PR DESCRIPTION
**Pull request by mikemaccana**
Also fix some typos and add link to Release Notes

### CODE REVIEW

**Comment by mikemaccana** [comment]
PS the markdown came from:

    $cmdLets = (Get-Module pscx).ExportedCmdlets.Keys
    $commands = (Get-Module pscx).ExportedCommands.Keys
    $cmdLetsAndCommands = $cmdLets + $commands | Sort-Object
    foreach ( $cmdLet in ($cmdLetsAndCommands) ) {
      $description = (get-help $cmdLet).synopsis.replace('PSCX Cmdlet: ','')
      $output = @'
    ### `{0}`

    {1}

    '@ -f $cmdLet, $description
      echo $output
    }

**Comment by mikemaccana** [comment]
Looks like `Add-PathVariable` is both a cmdlet and a command. No probs, will fix.

**Comment by mikemaccana** [comment]
Duplicates fixed! Also added the script itself.

**Comment by oising** [comment]
I think your confusion is coming from believing that there are two separate commands for Add-PathVariable and this is why your script is working off a completely incorrect assumption. With PowerShell, a "command" is a general term for cmdlets, functions, aliases, applications and external scripts. So by its very nature, any of these things is both itself AND a command. There is only one Add-PathVariable.

**Comment by mikemaccana** [comment]
Thanks Oisin. Understood re: cmdlets being a subset of commands. 

I've modified the script and result to use ExportedCmdlets and ExportedFunctions and remove the case filtering. 

Thanks for your patience / feedback on this PR - I'm relatively new to powershell so the feedback is much appreciated. I think PSCX is awesome and a README would help more people know how awesome it is before they install it. 🙂

**Comment by oising** [comment]
Much better. Thanks for your contribution, it's much appreciated. One more suggestion - personally I find when command lists are sorted by _noun_ rather than _verb_, more useful. I think it's easier then to get an overview of the extended functionality. What do you think?

**Comment by mikemaccana** [comment]
Good idea and done!

**Comment by oising** [comment]
Ok... now I think you're going to start regretting opening this pull request... but you seem to be missing a lot of commands now that I can see your output sorted. I'm not going to do your debugging for you, but look at this:

```
PS C:\projects\saputo\ios> gcm -noun ado* -module pscx

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-ADObject                                       3.3.0      pscx
Cmdlet          Get-AdoConnection                                  3.3.0      pscx
Cmdlet          Get-AdoDataProvider                                3.3.0      pscx
Cmdlet          Invoke-AdoCommand                                  3.3.0      pscx
```
In your list I don't see `Invoke-AdoCommand` for example. I'd imagine if you figure out why it's missing, you may end up getting the other missing commands too.

**Comment by mikemaccana** [comment]
Fixed! Let me know if you need anything else.

**Comment by mikemaccana** [comment]
Hey Oisin! Anything else to tick off? Keen to get this in! 🙂

**Comment by oising** [comment]
Done. Thank you for your contribution (and patience.)

**Comment by oising** [comment]
doh, meant to squash + merge. sigh. oh well, next time.

**Comment by rkeithhill** [comment]
@mikemaccana Nice! Thanks for your contribution.

**Pull request merged**
